'use strict';

/**
 * Standalone demo HTTP server — not wired to Vite or WorkspaceContext.
 * Generates a PDF from a tiny hardcoded JSON Resume via `lib/formatters/pdf`.
 *
 *   pnpm dev:api   # or: node app/server/index.js
 *
 *   GET http://localhost:8788/          → tiny HTML landing (link to PDF)
 *   GET http://localhost:8788/pdf-demo  → application/pdf (Chromium via Playwright)
 */

const http = require('node:http');
const path = require('node:path');
const { pathToFileURL } = require('node:url');

const PORT = Number.parseInt(process.env.PORT ?? '', 10) || 8788;

/** Minimal payload; `meta.skipValidation` skips full schema check in downstream paths if used later. */
const HARDCODED_RESUME = {
  meta: { skipValidation: true },
  basics: {
    name: 'PDF Demo',
    label: 'Hardcoded smoke test',
    email: 'demo@example.com',
    summary: 'This PDF is generated by app/server from static JSON — not the editor.',
    location: { city: 'Austin', region: 'TX', countryCode: 'US' },
    profiles: [],
  },
  work: [
    {
      name: 'Example Corp',
      position: 'Engineer',
      startDate: '2024-01-01',
      endDate: '',
      summary: 'Shipped the demo PDF endpoint.',
      highlights: ['Node + Playwright + jsonresume theme'],
    },
  ],
};

async function loadPdfFormatter() {
  const pdfPath = path.join(__dirname, '..', '..', 'lib', 'formatters', 'pdf.js');
  const mod = await import(pathToFileURL(pdfPath).href);
  return mod.default;
}

function sendText(res, status, body) {
  res.writeHead(status, { 'Content-Type': 'text/plain; charset=utf-8' });
  res.end(body);
}

function sendHtml(res, status, html) {
  res.writeHead(status, { 'Content-Type': 'text/html; charset=utf-8' });
  res.end(html);
}

function headersToObject(headers) {
  const out = {};
  for (const { key, value } of headers) {
    out[key] = value;
  }
  return out;
}

const server = http.createServer(async (req, res) => {
  const url = req.url ?? '/';

  if (req.method !== 'GET') {
    sendText(res, 405, 'Method Not Allowed\n');
    return;
  }

  if (url === '/' || url === '') {
    sendHtml(
      res,
      200,
      `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>PDF demo server</title>
</head>
<body style="font-family: system-ui, sans-serif; max-width: 40rem; margin: 2rem auto; line-height: 1.5;">
  <h1 style="font-size: 1.1rem;">PDF demo server (unwired)</h1>
  <p>The root URL is not a PDF — it is this landing page. Open the PDF route directly:</p>
  <p><a href="/pdf-demo" style="font-weight: 600;">Open /pdf-demo (generated PDF)</a></p>
  <p style="color: #555; font-size: 0.9rem;">Requires Playwright Chromium locally (<code>pnpm setup:browsers</code>). If generation fails, check the terminal for errors.</p>
</body>
</html>`,
    );
    return;
  }

  if (url.startsWith('/pdf-demo')) {
    try {
      const pdf = await loadPdfFormatter();
      const { content, headers } = await pdf.format(HARDCODED_RESUME, {
        theme: 'even',
        username: 'hardcoded-demo',
      });
      res.writeHead(200, headersToObject(headers));
      res.end(content);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      sendText(res, 500, `PDF generation failed: ${msg}\n`);
    }
    return;
  }

  sendText(res, 404, 'Not Found\n');
});

server.listen(PORT, () => {
  // eslint-disable-next-line no-console
  console.log(`[pdf-demo] listening on http://localhost:${PORT}/ (GET /pdf-demo for PDF)`);
});
